server:
  port : 8080
  servlet:
    session:
      timeout: 48h

spring:
  application:
    name: smartpost

  datasource:
    url: jdbc:mysql://localhost:3306/smartpost?serverTimezone=Asia/Tokyo&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5

    session:
      store-type: redis

    redis:
      host: localhost
      port: 6379

  data:
    elasticsearch:
      cluster-name: elasticsearch
      host: localhost
      port: 9300

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

ftp:
  host: 127.0.0.1
  port: 21
  username: ftpuser
  password: ftpuser
  filepath: /images