server:
  port : 8080
  servlet:
    session:
      timeout: 48h

spring:
  application:
    name: smartpost

  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

